### ISSUE TITLE
NAMUYANJA PATRICIA DCS EVENING 

### ISSUE THREAD

**Issue by Pasha-web** [drjeffgeoff/javaprojects#2]
public class MultidimensionalArray {
  public static void main(String args[]) {
     int [][]matrix={
       {1,2,3},
       {4,5,6},
       {7,8,9}
     };
     int element = matrix[1][2];
     System.out.println("The element is : " + element);
   }
}

**Comment by Pasha-web** [comment]
Multidimensional Array for element 6 only

**Comment by drjeffgeoff** [comment]
Code works fine, Please push it to your GitHub Account.
